# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.4
loader_version=0.16.10

# Fabric API
fabric_version=0.114.3+1.21.4
# Mod Properties
mod_version=2.0.0
maven_group=_2no2name
archives_base_name=Worldthreader

