# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=1.21.9
loader_version=0.17.2

# Fabric API
fabric_version=0.133.14+1.21.9

# Mod Properties
mod_version=2.5.1
maven_group=_2no2name
archives_base_name=Worldthreader
mod_name=Worldthreader


